### ISSUE TITLE
Map extent

### ISSUE THREAD

**Issue by luisortizuriarte** [bearlyonline/CLIM680#2]
Although your data is technically global, it might be better to cut off Antartica from the figure, since you are unlikely to have anthropogenic emissions there (or enough of them to map here).

Note: I could be wrong about this, so if you do expect values over Antartica do reply here!

**Comment by bearlyonline** [comment]
Antarctica is no longer on the map.

**Comment by luisortizuriarte** [comment]
The change satisfies my earlier comment. Closing issue.
