### ISSUE TITLE
Colormap choice

### ISSUE THREAD

**Issue by luisortizuriarte** [bearlyonline/CLIM680#3]
Sequential colormaps might be a better choice for your map here, since rainbow style colormaps are often hard to interpret (https://www.jstor.org/stable/24862699)

See here for matplotlib colormaps: https://matplotlib.org/stable/users/explain/colors/colormaps.html

**Comment by bearlyonline** [comment]
I changed it to a sequential color map on the fixed file added.

**Comment by luisortizuriarte** [comment]
Much better!

Closing issue.
